
// import config/cors
// const corsOptions = require("./config/cors")


/////////////////////////////////////////////////////////////
// Models
/////////////////////////////////////////////////////////////
// the people schema
// const ProductSchema = new mongoose.Schema({
//     name: String,
//     price: String,
//     department: String,
//     aisle: String,
//     image: String,
//     location: String
// }, {timestamps: true})

// const Products = mongoose.model("Products", ProductSchema)

// make a user schema
// const userSchema = new mongoose.Schema({
//   username: {type: String, required: true, unique: true},
//   password: {type: String, required: true}
// })

// Make the User Model
// const User = mongoose.model("User", userSchema)






// create a test route

// app.get("/", (req, res) => {
//     res.send("kweb is alive")
// })

 
  // create route
  // app.post("/products", async (req, res) => {
  //   try {
  //     // create a new product
  //     res.json(await Products.create(req.body));
  //   } catch (error) {
  //     res.status(400).json({ error });
  //   } 
  // });


  // update  route
//   app.put("/products/:id", async (req, res) => {
//     try {
//         // update a product
//         res.json(await Products.findByIdAndUpdate(req.params.id, req.body, {new: true}));
//       } catch (error) {
//         res.status(400).json({ error });
//       }
// })  

// Destroy Route 
// app.delete("/products/:id", async (req, res) => {
//   try {
//       // delete a products
//       res.json(await Products.findByIdAndRemove(req.params.id));
//     } catch (error) {
//       res.status(400).json({ error });
//     }
// })

  
// i put the commented out data here 